---
title: "Acceleration Tutorial"
author: "Maya Flannery"
format: html
editor: visual
---

## Reading files

### Setup and configuration

Set working directory to this notebook's location (`BEATmonitor/src/postprocess/scripts/`)

```{python}
import sys
sys.path.append("..")  # Allow imports from project directory
from bangle_process import data_access, utils, pipelines

utils.print_env_info() # Print environment information (check that it is activated)
```

Provide paths to the directory containing raw data, and to where processed data should be stored in `example_config.yml` (directory paths are relative to working directory).

Load the configuration:

```{python}
cfg = utils.load_config("example_config.yml")
```

Initialize directories:

```{python}
utils.init_directories(cfg)
```

### Get file summaries

Scan all files in the raw data directory:

```{python}
file_summary = data_access.summarise_files_in_directory(cfg)
```

View file metadata:

```{python}
View(file_summary)
```

### Flag bad records \[Not yet implemented for acceleration data\]

```{python}
# flagged_data = data_access.flag_records(files_watch_summary, cfg)
# files_watch_summary.drop(list(flagged_data.index), inplace=True)
```

### Read data

```{python}
df_raw = data_access.get_raw_watch_data(file_summary, cfg)
```

Since the watch files contain both heart rate and acceleration data, df_raw is a tuple with two dataframes:

-   HR data in `df_raw[0]`
-   Acceleration data in `df_raw[1]`

```{python}
df_raw_hr = df_raw[0]
df_raw_accel = df_raw[1]

print(df_raw_hr.info())
print(df_raw_accel.info())
```

### Data summaries

Use [Pandas](https://pandas.pydata.org/docs/) to manipulate dataframes:

```{python}
summary_raw_hr = df_raw_hr.groupby("watchId", observed=True).describe()
summary_raw_accel = df_raw_accel.groupby("watchId", observed=True).describe()
```

## Processing data

### Cropping

```{python}

```

### Resampling

TODO: Resampling method:

```{python}
def resample_df(
  df_in, downsample_rate=40, upsample_rate=10, upsample=True, interpolate=True, downsample=True
  ):
    df = df_in.copy()
    df.reset_index(inplace=True)
    df.drop(['index'], axis=1, inplace=True)
    df.set_index("time", inplace=True)
    
    if upsample and interpolate and downsample:
      # upsample: creates a time grid at upsample_rate milliseconds
      # interpolate: fill in NAs created by upsampling
      # downsample: create coarser time grid with mean of ohigh-res samples
      print("Upsample, interpolate, downsample")
      df_out = df.groupby("watchId", observed=True).apply(
          lambda g: (
              g.resample(f"{upsample_rate}ms")
              .mean()
              .interpolate(method="linear")
              .resample(f"{downsample_rate}ms")
              .last()
          )
      )
    elif upsample and interpolate:
      print("Upsample, interpolate")
      df_out = df.groupby("watchId", observed=True).apply(
          lambda g: (
              g.resample(f"{upsample_rate}ms")
              .mean()
              .interpolate(method="linear")
          )
      )
    elif upsample:
      print("Upsample")
      df_out = df.groupby("watchId", observed=True).apply(
          lambda g: (
              g.resample(f"{upsample_rate}ms")
              .mean()
          )
      )
    else:
      print("No resampling completed")
      return df_in
    
    return df_out.reset_index()
  
# Example: two second slice
df_ex = df_raw_hr[
  (df_raw_hr.time > "2025-06-09 15:47:50.080000-04:00") & 
  (df_raw_hr.time < "2025-06-09 15:47:52.080000-04:00")
  ]
  
# Pad with zeros, does this change shift in interpolation?

df_ex_UID.info()
df_ex_UID = resample_df(df_ex)
df_ex_UI = resample_df(df_ex, downsample=False)
df_ex_U = resample_df(df_ex, downsample=False, interpolate=False)
df_ex_NA = resample_df(df_ex, downsample=False, interpolate=False, upsample=False)
```

### TODO: Example plots

```{python}
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

fig, ax = plt.subplots(figsize=(20, 10))
# Set major ticks every 40 ms
ax.xaxis.set_major_locator(mdates.MicrosecondLocator(interval=40000))
ax.set_axisbelow(True)
ax.grid(True)

ax.scatter(df_ex_NA.time, df_ex_NA.ppgRaw, c="black", s=5)
ax.scatter(df_ex_U.time, df_ex_U.ppgRaw, c="green", s=30, alpha=0.5, marker="+")
ax.scatter(df_ex_UI.time, df_ex_UI.ppgRaw, c="blue", s=1, alpha=0.1)
ax.scatter(df_ex_UID.time, df_ex_UID.ppgRaw, c="red", s=5, alpha=0.5)
ax.plot(df_ex_UID.time, df_ex_UID.ppgRaw, c="red", alpha=0.1)

plt.show()

plt.savefig("ppg_plot.png", dpi=600, bbox_inches="tight")
plt.close()

df_ex_UID.head()
```

```{python}
df_accel_80ms = resample_df(df_raw_accel, sample_rate=80, interpolation_rate=1)
df_accel_80ms.head()
```
